/**
 * Automatically generated by @grafana/openapi-to-k6: 0.2.0
 * Do not edit manually.
 * Example API
 * API with all formats of query parameters
 * OpenAPI spec version: 1.0.0
 */
export type GetExampleData200 = {
  age?: number
  date?: string
  isActive?: boolean
  name?: string
  tags?: string[]
}

export type GetExampleDataParams = {
  /**
   * A string parameter
   */
  name: string
  /**
   * An integer parameter
   */
  age?: number
  /**
   * A boolean parameter
   */
  isActive?: boolean
  /**
   * An array of strings parameter
   */
  tags?: string[]
  /**
   * A date parameter in YYYY-MM-DD format
   */
  date?: string
}
