import fs from 'fs'
import os from 'os'
import path from 'path'
import { promisify } from 'util'
import { Mode } from '../../src/constants'
import generator from '../../src/generator'

const writeFile = promisify(fs.writeFile)
const readFile = promisify(fs.readFile)
const mkdtemp = promisify(fs.mkdtemp)
const rmdir = promisify(fs.rmdir)

const fixturesDir = path.join(__dirname, 'fixtures', 'schemas')

const loadFixture = (filename: string) => {
  const filePath = path.join(fixturesDir, filename)
  const data = fs.readFileSync(filePath, 'utf-8')
  return JSON.parse(data)
}

const commonSubstringsForAllSDK = [
  'Automatically generated by',
  'Do not edit manually',
  'OpenAPI spec version',
  'const mergedRequestParameters = this._mergeRequestParameters( requestParameters || {}, this.commonRequestParameters, );',
  'try { data = response.json(); } catch { data = response.body; }',
  'return { response, data, };',
]

const commonSubstringsForK6SampleScript = [`const baseUrl = "<BASE_URL>";`]

function replaceSpacesAndNewLineToSingleSpace(input: string): string {
  return input.replace(/\s+/g, ' ')
}

describe('generator', () => {
  let tempDir: string, schemaDirectory: string
  const allFixtures = fs.readdirSync(fixturesDir)

  beforeAll(async () => {
    tempDir = await mkdtemp(path.join(os.tmpdir(), 'sdk-generator-'))
  })

  afterAll(async () => {
    await rmdir(tempDir, { recursive: true })
  })

  for (const fixtureName of allFixtures) {
    describe(`test ${fixtureName} OpenAPI schema`, () => {
      let openApiPath: string, generatedSchemaPath: string
      const fixture = loadFixture(fixtureName)

      beforeEach(async () => {
        schemaDirectory = await mkdtemp(
          path.join(tempDir, fixtureName.replace('.', '-'))
        )
        // Write the OpenAPI schema to a file

        openApiPath = path.join(schemaDirectory, 'openapi-schema.json')

        await writeFile(openApiPath, JSON.stringify(fixture['openapi_schema']))

        generatedSchemaPath = path.join(schemaDirectory, 'generated-schema')
      })

      afterEach(async () => {
        await rmdir(schemaDirectory, { recursive: true })
      })

      it(`should generate SDK client from the OpenAPI schema`, async () => {
        const expectedGeneratedCode = fixture['expected_sdk']

        await generator({
          openApiPath,
          outputDir: generatedSchemaPath,
          mode: Mode.SINGLE,
        })

        const generatedFiles = fs.readdirSync(generatedSchemaPath)
        expect(generatedFiles.length).toBe(1)
        expect(generatedFiles[0]).toBeDefined()
        const fileName = path.basename(generatedFiles[0]!)
        expect(fileName).toBe(expectedGeneratedCode.fileName)
        const generatedFilePath = path.join(
          generatedSchemaPath,
          generatedFiles[0]!
        )
        const generatedContent = await readFile(generatedFilePath, 'utf-8')

        for (const expectedString of [
          ...expectedGeneratedCode['expectedSubstrings'],
          ...commonSubstringsForAllSDK,
        ]) {
          expect(
            replaceSpacesAndNewLineToSingleSpace(generatedContent)
          ).toContain(expectedString)
        }
      })

      it('should generate a sample K6 script', async () => {
        await generator({
          openApiPath,
          outputDir: generatedSchemaPath,
          shouldGenerateSampleK6Script: true,
          mode: Mode.SINGLE,
        })

        const generatedFiles = fs.readdirSync(generatedSchemaPath)
        expect(generatedFiles.length).toBe(2)
        const k6ScriptFile = generatedFiles.find((file) =>
          file.includes('k6-script')
        )
        expect(k6ScriptFile).toBeDefined()
        expect(k6ScriptFile).toBe('k6-script.sample.ts')

        const generatedFilePath = path.join(generatedSchemaPath, k6ScriptFile!)
        const generatedContent = await readFile(generatedFilePath, 'utf-8')

        for (const expectedString of [...commonSubstringsForK6SampleScript]) {
          expect(generatedContent).toContain(expectedString)
        }
      })
    })
  }
})
