import fs from 'fs'
import type { OpenApiDocument, OpenApiInfoObject } from '@orval/core'
import { generate as orval } from 'orval'
import path from 'path'
import { DEFAULT_SCHEMA_TITLE } from '../constants.js'
import { NoFilesGeneratedError } from '../errors.js'
import {
  formatFileWithPrettier,
  getPackageDetails,
  hasOnlyComments,
  OutputOverrider,
} from '../helper.js'
import { logger } from '../logger.js'
import { AnalyticsData, GenerateK6SDKOptions } from '../type.js'
import { getK6ClientBuilder } from './k6Client.js'

const outputOverrider = OutputOverrider.getInstance()
const packageDetails = getPackageDetails()

/**
 * Orval runs the input transformer before upgrading the spec to OpenAPI 3.1,
 * so this is the only place where the version declared by the user's spec is visible.
 * It also sets the default title for specs without one.
 */
const getInputTransformer =
  (analyticsData?: AnalyticsData) =>
  (spec: OpenApiDocument): OpenApiDocument => {
    if (analyticsData) {
      const { openapi, swagger } = spec as {
        openapi?: string
        swagger?: string
      }
      analyticsData.openApiSpecVersion = openapi ?? swagger ?? ''
    }

    return {
      ...spec,
      info: { ...spec.info, title: spec.info?.title || DEFAULT_SCHEMA_TITLE },
    }
  }

const SPEC_VALIDATION_ERROR_PREFIX = 'OpenAPI spec validation failed:'

const isSpecValidationError = (error: unknown): error is Error =>
  error instanceof Error &&
  error.message.startsWith(SPEC_VALIDATION_ERROR_PREFIX)

/**
 * Formats the validation errors reported by orval as one line per problem.
 * Falls back to the original message if it does not contain the expected list of errors.
 */
const formatSpecValidationErrors = (error: Error) => {
  try {
    const problems = JSON.parse(
      error.message.slice(SPEC_VALIDATION_ERROR_PREFIX.length)
    ) as { message: string; path: string }[]
    return problems
      .map(({ message, path }) => `- ${path}: ${message}`)
      .join('\n')
  } catch {
    return error.message
  }
}

const generatedFileHeaderGenerator = (info: OpenApiInfoObject) => {
  return [
    `Automatically generated by ${packageDetails.name}: ${packageDetails.version}`,
    `Do not edit manually.`,
    ...(info.title ? [info.title] : []),
    ...(info.description ? [info.description] : []),
    ...(info.version ? [`Service version: ${info.version}`] : []),
  ]
}

const afterAllFilesWriteHandler = async (
  filePaths: string[],
  outputOverrider: OutputOverrider
) => {
  const removeSingleFile = (filePath: string) => {
    try {
      fs.unlinkSync(filePath)
    } catch (error) {
      // This is non-critical, so we just log it
      logger.debug(
        `afterAllFilesWriteHandler ~ Error deleting file ${filePath}: ${error}`
      )
    }
  }
  const emptyFileList: string[] = []

  for (const filePath of filePaths) {
    // There is a bug in the orval library which generates empty files when tags filter is applied
    // and no matching endpoints are found and used mode is split or single.
    // It generates the file with only the header comment.
    // Hence, we manually remove those empty files.
    // Issue link - https://github.com/orval-labs/orval/issues/1691

    const fileContent = fs.readFileSync(filePath, 'utf-8')
    if (hasOnlyComments(fileContent)) {
      emptyFileList.push(filePath)
      // Delete the file
      removeSingleFile(filePath)
      continue
    }

    // Replace usages of Blob type (and the `Blob | File` union used for form data)
    // with the k6-compatible ArrayBuffer
    const newFileContent = fileContent.replaceAll(
      /(^|\W)Blob(?:\s*\|\s*File)?(?!\w)/g,
      '$1ArrayBuffer'
    )

    fs.writeFileSync(filePath, newFileContent)

    try {
      await formatFileWithPrettier(filePath)
    } catch (error) {
      await outputOverrider.temporarilyWriteToStdoutAndStderr(async () => {
        logger.error(`Error in formatting file ${filePath}: ${error}`)
      })
    }

    const fileName = path.basename(filePath)

    if (fileName === '.ts') {
      // Generated SDK had no name because there was no title in the schema
      // Rename it to the default name
      const directoryPath = path.dirname(filePath)
      const newPath = path.join(directoryPath, `${DEFAULT_SCHEMA_TITLE}.ts`)
      logger.debug(
        `afterAllFilesWriteHandler ~ Renaming ${filePath} to ${newPath}`
      )
      fs.renameSync(filePath, newPath)
    }
  }

  if (emptyFileList.length > 0) {
    logger.debug(
      `afterAllFilesWriteHandler ~ The following files were empty and removed: ${emptyFileList.join(
        ', '
      )}`
    )
  }

  // Return the list of generated file paths excluding the empty files
  const filteredFilePaths = filePaths.filter(
    (filePath) => !emptyFileList.includes(filePath)
  )

  // Check if all the filtered file path end with `.schemas.ts`
  if (filteredFilePaths.every((filePath) => filePath.endsWith('.schemas.ts'))) {
    // If yes we should remove them as only schemas files is not needed
    filteredFilePaths.map(removeSingleFile)
    return []
  }

  return filteredFilePaths
}

export default async ({
  openApiPath,
  outputDir,
  shouldGenerateSampleK6Script,
  analyticsData,
  mode,
  tags,
}: GenerateK6SDKOptions) => {
  /**
   * Note!
   * 1. override.requestOptions is not supported for the custom K6 client
   * 2. override.mutator is not supported for the custom K6 client
   */
  const generatedFilePaths: string[] = []
  const generate = async (unsafeDisableValidation: boolean) => {
    try {
      await orval(
        {
          input: {
            target: openApiPath,
            filters: {
              tags: tags && tags.length > 0 ? tags : undefined,
              includeUnreferencedSchemas: true,
            },
            override: {
              transformer: getInputTransformer(analyticsData),
            },
            unsafeDisableValidation,
          },
          output: {
            target: outputDir,
            mode: mode,
            client: () =>
              getK6ClientBuilder(shouldGenerateSampleK6Script, analyticsData),
            override: {
              header: generatedFileHeaderGenerator,
            },
            headers: true,
            // Orval otherwise picks up the nearest tsconfig.json from the working directory,
            // which changes import extensions and import style in the generated code.
            tsconfig: { compilerOptions: { esModuleInterop: true } },
          },
          hooks: {
            afterAllFilesWrite: async (...args: unknown[]) => {
              const filePaths = args[0] as string[]
              const filteredFilePaths = await afterAllFilesWriteHandler(
                filePaths,
                outputOverrider
              )
              generatedFilePaths.push(...filteredFilePaths)
            },
          },
        },
        undefined,
        { throwOnError: true }
      )
    } catch (error) {
      if (isSpecValidationError(error)) {
        throw error
      }
      // Other errors are already logged by orval, and are reported below
      // as no files being generated
    }
  }

  await outputOverrider.redirectOutputToNullStream(async () => {
    try {
      await generate(false)
    } catch (error) {
      if (!isSpecValidationError(error)) {
        throw error
      }
      // Older versions of orval did not validate the spec, so fall back to
      // generating without validation to keep such specs working
      await outputOverrider.temporarilyWriteToStdoutAndStderr(async () => {
        logger.warning(
          `The OpenAPI schema is invalid, generating the client anyway. Generated code might be incorrect.\n${formatSpecValidationErrors(error)}`
        )
      })
      await generate(true)
    }
  })

  if (generatedFilePaths.length === 0) {
    const tagsMessage =
      tags?.length && tags.length > 0
        ? ` Applied tag filter(s): ${tags.join(', ')}. `
        : ' '
    throw new NoFilesGeneratedError(
      `No files were generated.${tagsMessage}Try running with --verbose flag to get more details.`
    )
  }
}
