import fs from 'fs'
import os from 'os'
import path from 'path'
import {
  afterAll,
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
} from 'vitest'
import { Mode } from '../../../src/constants'
import generator from '../../../src/generator'

import {
  loadFixture,
  mkdtemp,
  readFile,
  replaceSpacesAndNewLineToSingleSpace,
  rmdir,
  writeFile,
} from '../helper'

const commonSubstringsForAllSDK = [
  'Automatically generated by',
  'Do not edit manually',
  'Service version',
  'const mergedRequestParameters = this._mergeRequestParameters( requestParameters || {}, this.commonRequestParameters, );',
  'try { data = response.json(); } catch { data = response.body; }',
]

const commonMatchesForAllSDK = [
  /return { response, data, operationId: "[^"]*", };/,
]

const commonSubstringsForK6SampleScript = [`const baseUrl = "<BASE_URL>";`]

describe('generator', () => {
  let tempDir: string, schemaDirectory: string
  const allFixtures = fs.readdirSync(path.join(__dirname, 'fixtures'))

  beforeAll(async () => {
    tempDir = await mkdtemp(path.join(os.tmpdir(), 'sdk-generator-'))
  })

  afterAll(async () => {
    await rmdir(tempDir, { recursive: true })
  })

  for (const fixtureName of allFixtures) {
    describe(`test ${fixtureName} OpenAPI schema`, () => {
      let openApiPath: string, generatedSchemaPath: string
      const fixture = loadFixture(path.join(__dirname, 'fixtures', fixtureName))

      beforeEach(async () => {
        schemaDirectory = await mkdtemp(
          path.join(tempDir, fixtureName.replace('.', '-'))
        )
        // Write the OpenAPI schema to a file

        openApiPath = path.join(schemaDirectory, 'openapi-schema.json')

        await writeFile(openApiPath, JSON.stringify(fixture['openapi_schema']))

        generatedSchemaPath = path.join(schemaDirectory, 'generated-schema')
      })

      afterEach(async () => {
        await rmdir(schemaDirectory, { recursive: true })
      })

      it(`should generate SDK client from the OpenAPI schema`, async () => {
        const expectedGeneratedCode = fixture['expected_sdk']

        await generator({
          openApiPath,
          outputDir: generatedSchemaPath,
          mode: Mode.SINGLE,
        })

        const generatedFiles = fs.readdirSync(generatedSchemaPath)
        expect(generatedFiles.length).toBe(1)
        expect(generatedFiles[0]).toBeDefined()
        const fileName = path.basename(generatedFiles[0]!)
        expect(fileName).toBe(expectedGeneratedCode.fileName)
        const generatedFilePath = path.join(
          generatedSchemaPath,
          generatedFiles[0]!
        )
        const generatedContent = await readFile(generatedFilePath, 'utf-8')

        for (const expectedString of [
          ...expectedGeneratedCode['expectedSubstrings'],
          ...commonSubstringsForAllSDK,
        ]) {
          expect(
            replaceSpacesAndNewLineToSingleSpace(generatedContent)
          ).toContain(expectedString)
        }
        for (const expectedToMatch of commonMatchesForAllSDK) {
          expect(
            replaceSpacesAndNewLineToSingleSpace(generatedContent)
          ).toMatch(expectedToMatch)
        }
      })

      it('should generate a sample K6 script', async () => {
        await generator({
          openApiPath,
          outputDir: generatedSchemaPath,
          shouldGenerateSampleK6Script: true,
          mode: Mode.SINGLE,
        })

        const generatedFiles = fs.readdirSync(generatedSchemaPath)
        expect(generatedFiles.length).toBe(2)
        const k6ScriptFile = generatedFiles.find((file) =>
          file.includes('k6-script')
        )
        expect(k6ScriptFile).toBeDefined()
        expect(k6ScriptFile).toBe('k6-script.sample.ts')

        const generatedFilePath = path.join(generatedSchemaPath, k6ScriptFile!)
        const generatedContent = await readFile(generatedFilePath, 'utf-8')

        for (const expectedString of [...commonSubstringsForK6SampleScript]) {
          expect(generatedContent).toContain(expectedString)
        }
      })

      it('should not contain types in main file when using split mode', async () => {
        await generator({
          openApiPath,
          outputDir: generatedSchemaPath,
          shouldGenerateSampleK6Script: true,
          mode: Mode.SPLIT,
        })
        const expectedGeneratedCode = fixture['expected_sdk']
        const generatedFiles = fs.readdirSync(generatedSchemaPath)

        expect(generatedFiles.length).toBe(3)

        const clientFile = generatedFiles.find((file) =>
          file.includes(expectedGeneratedCode.fileName)
        )
        const schemaFile = generatedFiles.find((file) =>
          file.includes('.schemas.ts')
        )

        expect(clientFile).toBeDefined()
        expect(schemaFile).toBeDefined()

        const generatedFilePath = path.join(generatedSchemaPath, clientFile!)
        const generatedContent = await readFile(generatedFilePath, 'utf-8')
        expect(generatedContent).not.toContain('export type')
        expect(generatedContent).not.toContain('export interface')
      })
    })
  }

  describe('prepared requests', () => {
    const fixture = loadFixture(
      path.join(__dirname, 'fixtures', 'headers_schema.json')
    )

    async function generatePreparedRequestsFixture() {
      const directory = await mkdtemp(path.join(tempDir, 'prepared-requests-'))
      const openApiPath = path.join(directory, 'openapi-schema.json')
      const outputDir = path.join(directory, 'generated-schema')
      await writeFile(openApiPath, JSON.stringify(fixture['openapi_schema']))
      await generator({
        openApiPath,
        outputDir,
        mode: Mode.SINGLE,
        shouldGeneratePreparedRequests: true,
      })

      const [generatedFile] = fs.readdirSync(outputDir)
      const content = await readFile(
        path.join(outputDir, generatedFile!),
        'utf-8'
      )
      await rmdir(directory, { recursive: true })
      return replaceSpacesAndNewLineToSingleSpace(content)
    }

    it('generates prepared requests and batch execution when enabled', async () => {
      const generatedContent = await generatePreparedRequestsFixture()

      expect(generatedContent).toContain(
        'prepareGetExampleGet( headers?: GetExampleGetHeaders, requestParameters?: Params, ): PreparedRequest<GetExampleGet200>'
      )
      expect(generatedContent).toContain(
        'return this.execute(this.prepareGetExampleGet(headers, requestParameters));'
      )
      expect(generatedContent).toContain(
        'body: JSON.stringify(postExamplePostBody)'
      )
      expect(generatedContent).toContain(
        'return response.json() as unknown as GetExampleGet200'
      )
      expect(generatedContent).toContain('parse: () => undefined')
      expect(generatedContent).toContain(
        'batch<const Requests extends readonly PreparedRequest<unknown>[]>( preparedRequests: Requests, ): BatchResults<Requests>'
      )
      expect(generatedContent).toContain(
        'const responses = http.batch( preparedRequests.map(({ request }) => request), );'
      )
    })
  })
})
